[package]
name = "fngr"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
maplit = "1.0.2"
sha2 = "0.10.9"
tokio = { version = "1.49.0", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
uuid = "1.19.0"
